config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'todos#index'

  resources :todos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  VALID_STATUSES = %w[pending completed]

  validates :todo, presence: true
  validates :status, inclusion: { in: VALID_STATUSES }

  after_initialize :set_defaults, unless: :persisted?

  def pending?
    status == 'pending'
  end

  def set_defaults
    self.status ||= 'pending'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.order(status: :desc)
    @todo = Todo.new
  end

  def create
    @todo = Todo.create(todo_params)

    if @todo.save
      redirect_to action: 'index'
    else
      @todos = Todo.order(status: :desc)
      render :index
    end
  end

  def update
    @todo = Todo.find(params[:id])

    @todo.status = params[:status]

    @todo.save

    redirect_to action: 'index'
  end

  def destroy
    @todo = Todo.find(params[:id])

    @todo.destroy

    redirect_to action: 'index'
  end

  private

  def todo_params
    params.require(:todo).permit(:todo, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with class: "mt-3", model: todo do |form| %>
        <div class="d-flex w-50">
            <div class="w-100 me-2">
                <%= form.text_field :todo, placeholder: "New Todo....", class: "form-control w-100 #{'is-invalid' unless todo.errors.full_messages_for(:todo).empty?}" %>
                <% todo.errors.full_messages_for(:todo).each do |message|%>
                    <div class="invalid-feedback"> <%=message%> </div>
                <%end%>
            </div>
            <div>
                <%= form.submit "Add Todo", class:"btn btn-primary flex-grow-0" %>
            </div>
        </div>
<% end %>
       

app/views/todos/_todo-item.html.erb
<li class="list-group-item d-flex w-50 pe-0">
            <span class="w-100 me-2 <%= 'text-muted completed' unless todo.pending? %>"> <%= todo.todo%> </span>
            <% if todo.pending? %>
                <%= button_to "Complete", todo_path(todo.id), method: :put, params: { status: "completed"}, class: "btn btn-outline-success" %>
            <% else%>
                <%= button_to "Uncheck", todo_path(todo.id), method: :put, params: { status: "pending"}, class: "btn btn-outline-secondary" %>
            <% end %>
            <%= button_to "Delete", todo_path(todo.id), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-outline-danger ms-1" %>
</li>

app/views/todos/index.html.erb
<main class="container pt-5">
    <h1> Todos</h1>
    <%= render "form", todo: @todo%>
    <ul class="list-group list-group-flush mt-4 w-100">
    <% @todos.each do |todo| %>
        <%= render "todo-item", todo: todo%>
    <% end %>
    </ul>
</main>